name: Pylint

on:
  push:
    paths:
      - '*.py'

jobs:
  lint:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install pylint
        python -m pip install flake8

    - name: Lint code
      run: |
        for /f "tokens=*" %%i in ('git diff --name-only HEAD^1') do (
            echo %%i| findstr ".py$" >nul
            if errorlevel 1 (
                echo "%%i is not a python file"
            ) else (
                pylint %%i
                flake8 %%i
            )
        )

    - name: Check Pylint score
      run: |
        set PYLINT_SCORE=0
        for /f "tokens=*" %%i in ('git diff --name-only HEAD^1') do (
            echo %%i| findstr ".py$" >nul
            if errorlevel 1 (
                echo "%%i is not a python file"
            ) else (
                set /a PYLINT_SCORE += $(pylint --output-format=parseable %%i | awk '{ if ($1 ~ /^[0-9]*\./) { total += $1 * 10 } } END { print total / NR }')
            )
        )
        echo "Pylint Score: %PYLINT_SCORE%"
        if %PYLINT_SCORE% lss 8 (
            echo "Pylint score is below 8, failing build."
            exit 1
        )