name: Python test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Linting with Python
      uses: gabriel-milan/action-pylint@v1
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
        path: "./*.py" # Glob pattern for files to lint
        fail: true # Fail the action if pylint errors are found
        pr-message: true # Send a PR message if pylint errors are found
