name: Pylint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install pylint
    - name: Get modified python files
      run: git diff --name-only origin/main...HEAD | grep '\.py$' > modified_files.txt

    - name: Run pylint
      run: cat modified_files.txt | xargs -I % sh -c 'pylint % -r --output-format=json > log.json'
    - name: Upload log file
      uses: actions/upload-artifact@v2
      with:
        name: log
        path: modified_files.txt
