name: Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pylint

    - name: Lint code
      run: |
        pylint ./*.py

    - name: Update status
      uses: actions/github-script@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const context = github.context;
          const { owner, repo } = context.repo;
          
          // Check if the linting step failed
          if (process.exitCode !== 0) {
            github.repos.createStatus({
              owner,
              repo,
              context: 'Linting',
              sha: context.sha,
              state: 'failure',
              target_url: 'https://github.com/actions',
              description: 'Linting checks failed',
              headers: {
                accept: 'application/vnd.github+json'
              }
            });
            return;
          }

          // Linting checks passed
          github.repos.createStatus({
            owner,
            repo,
            context: 'Linting',
            sha: context.sha,
            state: 'success',
            target_url: 'https://github.com/actions',
            description: 'Linting checks passed',
            headers: {
              accept: 'application/vnd.github+json'
            }
          });
