name: Linting on Pull Request

on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  lintonPR:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install pylint_runner
    - name: Run linter
      run: |
        # replace with the appropriate linter command for your project
        pylint_runner
